version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - network-bank
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - network-bank
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - network-bank
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
  postgres:
    image: postgres:latest
    networks:
      - network-bank
    container_name: postgres-bank
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  wiremock_cadastro:
    image: "wiremock/wiremock"
    command: --global-response-templating --https-port 8443 --verbose
    ports:
      - 48080:8080
      - 48443:8443
    volumes:
      - ./local/wiremock/cadastro:/home/wiremock
    container_name: wiremock_cadastro
  wiremock_bacen:
    image: "wiremock/wiremock"
    command: --global-response-templating --https-port 8443 --verbose
    ports:
      - 58080:8080
      - 58443:8443
    volumes:
      - ./local/wiremock/bacen:/home/wiremock
    container_name: wiremock_bacen

networks:
  network-bank:
    driver: bridge