server:
  port: 8070

client:
  url: http://localhost:8091
  kafka-host: 127.0.0.1:9092
  feign:
    bank-kernel:
      url: http://localhost:8090
      cache-ttl: 15

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      detail-service:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 7
        failure-rate-threshold: 30
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 20ms
        permitted-number-of-calls-in-half-open-state: 2
        register-health-indicator: true
